# Generated by Django 3.1 on 2020-10-04 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_cmmsuser_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmmsuser',
            name='group',
        ),
    ]
