# Generated by Django 3.1 on 2020-10-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_smansauser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='smansauser',
            name='verified_by',
            field=models.IntegerField(default=0),
        ),
    ]
